### ISSUE TITLE
Export commands so that kpm can install xunit.runner.kre globally

### ISSUE THREAD

**Issue by victorhurdugaci** [xunit/dnx.xunit#14]
We've added support for [installing tools globally using `kpm commands`](https://github.com/aspnet/XRE/pull/1154)

It would be nice if xunit could be installed globally that way. All it needs is a command in the `commands` section in `project.json`

Today it doesn't work because of that: https://github.com/aspnet/XRE/issues/540#issuecomment-75273122

**Comment by bradwilson** [comment]
I think we need some of the ASP.NET team (@davidfowl, @damianedwards) to jump in and help me understand what changes they're planning to make to the unit testing infrastructure, because I'm pretty sure today that the "test" command is looked for specially by their Visual Studio infrastructure. Having global commands would imply that (a) their infrastructure would look there, too; and (b) the "test" command can't be special any more, because I presume users will want to have multiple test frameworks installed into their global space.

**Comment by bradwilson** [comment]
After talking to @davidfowl last night, I'm going to use the command "xunit", as it appears that globally installed "apps" have nothing to do with Visual Studio support, so the name should be specific to test framework.

**Comment by bradwilson** [comment]
Also, I've put this in the [dnvm branch](https://github.com/xunit/aspnet.xunit/tree/dnvm) since this feature is not supported by KRE 1.0 Beta 3.

**Comment by victorhurdugaci** [comment]
Cool. Thanks!

**Comment by bradwilson** [comment]
Shipping with 2.1 Beta 2.
